#!bin/zsh


# Check for psql command
if ! command -v psql &> /dev/null
then
    echo "psql command not found. Please install PostgreSQL and ensure psql is in your PATH."
    exit 1
fi

# Drop the database if it exists
psql -U wellzhang -c "DROP DATABASE IF EXISTS papergo;"

# Create the new database
psql -U wellzhang -c "CREATE DATABASE papergo;"

echo "Database 'papergo' setup successfully."

export DATABASE_PATH='postgresql://wellzhang@localhost:5432/papergo'
echo 'setup.sh script executed successfully!'

# export TEST_JWT_TOKEN='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9YZF93QlV0ZUxIckFqSEFaVVBFYiJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZDZpcGhsMmhkdDA1ODJ3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NGU3ODNjNTA4NmY5MGRhMTQyNWE3OWEiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTY5MjkwMDA2NCwiZXhwIjoxNjkyOTA3MjY0LCJhenAiOiJHdWdoTWFGdmJXbU1jSFBES2dGSEIzUmlhZk5OT2NZZyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmRpc2NvdmVyeSIsImdldDpkaXNjb3ZlcmllcyIsImdldDp1c2VyIiwicGF0Y2g6ZGlzY292ZXJ5IiwicG9zdDpkaXNjb3ZlcnkiLCJzZWFyY2g6ZGlzY292ZXJpZXMiXX0.GWwvHn8stOPrLWB5qzfryurbno_RN71JIugIyKeAl9ywY_pdXH3kPbeze3pRtZ2fR497ELnErqHsoATFAlHxXYd3EWtGOJp1fFELLaWDdpZu-vdlmOlRAnGDlrGxT7UgbuEIsNlL70vlgjP50mOw0x3nB7HIDM9-GJpbVo4s2egZ0ZhzedqYXbC91TToVwDbY8LajQm1fFMiVTl0mX8jOHWTzjMUfvpJUt6-vnj7pnVAe7MUA2uXrgvGPAfjfozTslgFNNmCbVMuXkmV8fZCn7ZY8Joagg13VVEYJtzc2MF4Wu4AF0-E3mjA2NgIEznCkWaaGu5rnXZAHItVZ08A7g'
# export DISCOVERIES_PER_PAGE=10
# export AUTH0_DOMAIN='dev-qd6iphl2hdt0582w.us.auth0.com'
# export API_AUDIENCE='capstone'
# export CLIENTID='GughMaFvbWmMcHPDKgFHB3RiafNNOcYg'
# export CLIENTSECRET='BDLhkUZHhP7jJltJxxX3eQLNM5ADgd2keJ9QS3ZFVfig-2mP7C2mCaw2-bdWYZC6'
# export REDIRECT_URI='https://render-deployment-example-n2d0.onrender.com/playground'
# export USER_JWT='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9YZF93QlV0ZUxIckFqSEFaVVBFYiJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZDZpcGhsMmhkdDA1ODJ3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NGU2ZjA2NTEwY2E3N2E1ZWU5MmMyN2EiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTY5MjkwMzM4MywiZXhwIjoxNjkyOTEwNTgzLCJhenAiOiJHdWdoTWFGdmJXbU1jSFBES2dGSEIzUmlhZk5OT2NZZyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZ2V0OmRpc2NvdmVyaWVzIiwiZ2V0OnVzZXIiLCJwYXRjaDpkaXNjb3ZlcnkiLCJwb3N0OmRpc2NvdmVyeSIsInNlYXJjaDpkaXNjb3ZlcmllcyJdfQ.T50aae8faC9bLcpD5wHIa2r1jjebhIAm5xGZQI7nCLumu-mL7TGKprDiTiBSWzEvcEDORRMg9XNBI7JcyOfhEHWZlGmqRX8uuycZF-_jrCCXYQjz-cHry8pFCBCq5Q-Lq_olxz6C-o-KjOKXsKKpaAnhs-dLh9D4AKH7H1P2WndSe9wimRN-eRNkD34Sjg4lvesWzQugKDZAuSzBLmJgSaYpBG4C4vSe5_cYdWemrEa9EO9DqgRqVB89IOMEHL_EqjH8uuumvXO9dYR1OGhNY7PQsYP3Oo8zLWGtPAwXMBKY4J7hU0Sbks8zaaPMx5q2pxzhuB-x8B6YVu4rdAjvLw'
# export PREMIUMER_JWT='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9YZF93QlV0ZUxIckFqSEFaVVBFYiJ9.eyJpc3MiOiJodHRwczovL2Rldi1xZDZpcGhsMmhkdDA1ODJ3LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw2NGU2ZjQ2MDc2OGQ0NzZlMzgyMDg1YjEiLCJhdWQiOiJjYXBzdG9uZSIsImlhdCI6MTY5MjkwMzI4NCwiZXhwIjoxNjkyOTEwNDg0LCJhenAiOiJHdWdoTWFGdmJXbU1jSFBES2dGSEIzUmlhZk5OT2NZZyIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmRpc2NvdmVyeSIsImdldDpkaXNjb3ZlcmllcyIsImdldDp1c2VyIiwicGF0Y2g6ZGlzY292ZXJ5IiwicG9zdDpkaXNjb3ZlcnkiLCJzZWFyY2g6ZGlzY292ZXJpZXMiXX0.N-WICVQujPwIsmZtJaFHss6dmmdnY9y3HKojhpf9X55AivISQrqniK7Z4xOPcBFh4c-v65486p1ryCcsS90DepTaBoKbvgxUQWTDJGFPMFvyIHq0FneYulzq7Mcr2fDbUZgX7TwkBV7xvNHm-rXeJDMKfAsvRLGKjx4qE9YPixmc7SRumLK7DOF2IeaD-nhVoCKuQBwYx3Ol08NIbJ7M76QOmGEfNXkX_OVgAzEzw97D4s-Slogbc908AqFCGkpZwUIwVpRTl1dfNX_s7nXBn0NBNRgm39KtLv0i-6drhICdBB9xtw1r7iYLpjHt7frfCoFal5-lb5FtX7V2vKYNmw'

